src/Entity/Roles.php
<?php

namespace App\Entity;

use App\Repository\RolesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RolesRepository::class)]
class Roles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $role_name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'role', targetEntity: User::class)]
    private Collection $users;

    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'role')]
    private Collection $category;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoleName(): ?string
    {
        return $this->role_name;
    }

    public function setRoleName(string $role_name): static
    {
        $this->role_name = $role_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Users>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setRoles($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getRoles() === $this) {
                $user->setRoles(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, categories>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
            $category->addRole($this);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }
}

src/Form/RolesType.php
<?php

namespace App\Form;

use App\Entity\Roles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Categories;

class RolesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('role_name')
            ->add('category', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'category_name',
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Roles::class,
        ]);
    }
}

src/Controller/RolesController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\Roles;
use App\Form\RolesType;
use App\Repository\RolesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/roles')]
class RolesController extends AbstractController
{
    #[Route('/', name: 'app_roles_index', methods: ['GET'])]
    public function index(RolesRepository $rolesRepository): Response
    {
        if (!$this->isUserAdmin()) {
            throw new AccessDeniedException('Access denied: You do not have permission to go there.');
        }
        return $this->render('roles/index.html.twig', [
            'roles' => $rolesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_roles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $role = new Roles();
        $form = $this->createForm(RolesType::class, $role);
        $form->handleRequest($request);
        $role->setCreatedAt(new \DateTimeImmutable());

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($role);
            $entityManager->flush();

            return $this->redirectToRoute('app_roles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('roles/new.html.twig', [
            'role' => $role,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_roles_show', methods: ['GET'])]
    public function show(Roles $role): Response
    {
        return $this->render('roles/show.html.twig', [
            'role' => $role,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_roles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Roles $role, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RolesType::class, $role);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formData = $form->getData();
            // Récupérez les catégories sélectionnées à partir des données soumises
            $selectedCategories = $formData->getCategory();
            $selectedCategoryNames = [];
            foreach ($selectedCategories as $category) {
                $role->addCategory($category);
                $selectedCategoryNames[] = $category->getCategoryName();
            }


            // Sauvegardez le rôle, il sera mis à jour avec la nouvelle catégorie sélectionnée
            $entityManager->flush();
            return $this->redirectToRoute('app_roles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('roles/edit.html.twig', [
            'role' => $role,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_roles_delete', methods: ['POST'])]
    public function delete(Request $request, Roles $role, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $role->getId(), $request->request->get('_token'))) {
            $entityManager->remove($role);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_roles_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/assign-category/{categoryId}', name: 'app_roles_assign_category')]
    public function assignCategory(Request $request, Roles $role, Categories $category, EntityManagerInterface $entityManager): Response
    {
        // Ajoutez le rôle à la catégorie s'il n'est pas déjà présent
        if (!$category->getRoles()->contains($role)) {
            $category->addRole($role);
            $role->addCategory($category); // Assurez-vous d'ajouter la catégorie au rôle
            $entityManager->persist($category);
            $entityManager->persist($role); // N'oubliez pas de persister le rôle
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_categories_show', ['id' => $category->getId()]);
    }
    private function isUserAdmin(): bool
    {
        // Récupérez l'utilisateur connecté
        $user = $this->getUser();
        // Si l'utilisateur n'est pas connecté ou s'il n'a pas le rôle "admin", il n'a pas l'autorisation
        if (!$user || !in_array('admin', $user->getRoles())) {
            return false;
        }

        // L'utilisateur a le rôle "admin" et est autorisé
        return true;
    }
}

templates/roles/_delete_form.html.twig
<form method="post" action="{{ path('app_roles_delete', {'id': role.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ role.id) }}">
    <button class="btn">Delete</button>
</form>

templates/roles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/roles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Roles{% endblock %}

{% block body %}
    <h1>Edit Roles</h1>

    {{ include('roles/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_roles_index') }}">back to list</a>

    {{ include('roles/_delete_form.html.twig') }}
{% endblock %}

templates/roles/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Roles index{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Role Management</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Role_name</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
            {% for role in roles %}
                <tr>
                    <td>{{ role.roleName }}</td>
                    <td>{{ role.createdAt ? role.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>
                        <a href="{{ path('app_roles_show', {'id': role.id}) }}">show</a>
                        <a href="{{ path('app_roles_edit', {'id': role.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

<div class="text-center">
    <a href="{{ path('app_roles_new') }}">Create a new role</a></br>
    <a href="{{ path('app_home') }}">Back to home</a>
    </div>
</div>
{% endblock %}

templates/roles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Roles{% endblock %}

{% block body %}
    <h1>Create new Roles</h1>

    {{ include('roles/_form.html.twig') }}

    <a href="{{ path('app_roles_index') }}">back to list</a>
{% endblock %}

templates/roles/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Roles{% endblock %}

{% block body %}
<style>
.text-center{
    text-align: center;
}
    .example-wrapper { margin: 1em auto; max-width: 1240px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        padding-bottom: 1em;
    }
    .table th, .table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    .table th {
        background-color: #f2f2f2;
        display: flex;
        justify-content: space-between;
        padding: 1em;
    }
    .table th div {
        display: flex;
    }
    .table th div a {
        margin-right: 0.5em;
    }
</style>
<div class="example-wrapper">
    <h1>{{ role.roleName }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ role.roleName|upper }}
                    <div>
                        <a href="{{ path('app_roles_edit', {'id': role.id}) }}">edit</a>
                        {{ include('roles/_delete_form.html.twig') }}
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Id</td>
                <td>{{ role.id }}</td>
            </tr>
            <tr>
                <td>Role_name</td>
                <td>{{ role.roleName }}</td>
            </tr>
            <tr>
                <td>Created_at</td>
                <td>{{ role.createdAt ? role.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

<div class="text-center">
    <a href="{{ path('app_roles_index') }}">back to list</a></br>

    <a href="{{ path('app_home') }}">back to home</a>
    </div>
</div>
{% endblock %}