src/Entity/Board.php
<?php

namespace App\Entity;

use App\Repository\BoardRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoardRepository::class)]
class Board
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $board_name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'boards')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $category = null;

    #[ORM\OneToMany(mappedBy: 'board', targetEntity: Topic::class)]
    private Collection $topics;

    public function __construct()
    {
        $this->topics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoardName(): ?string
    {
        return $this->board_name;
    }

    public function setBoardName(string $board_name): static
    {
        $this->board_name = $board_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Topic>
     */
    public function getTopics(): Collection
    {
        return $this->topics;
    }

    public function addTopic(Topic $topic): static
    {
        if (!$this->topics->contains($topic)) {
            $this->topics->add($topic);
            $topic->setBoard($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): static
    {
        if ($this->topics->removeElement($topic)) {
            // set the owning side to null (unless already changed)
            if ($topic->getBoard() === $this) {
                $topic->setBoard(null);
            }
        }

        return $this;
    }
}

src/Entity/Topic.php
<?php

namespace App\Entity;

use App\Repository\TopicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TopicRepository::class)]
class Topic
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column]
    private ?int $number_view = 0;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'topics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Board $board = null;

    #[ORM\ManyToOne(inversedBy: 'topics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'topic', targetEntity: Message::class)]
    private Collection $messages;

    #[ORM\Column(length: 255, nullable: true)]
    private $imageFileName;

    /**
     * @var UploadedFile|null
     */
    private $imageFile;


    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getNumberView(): ?int
    {
        return $this->number_view;
    }

    public function setNumberView(int $number_view): static
    {
        $this->number_view = $number_view;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getBoard(): ?Board
    {
        return $this->board;
    }

    public function setBoard(?Board $board): static
    {
        $this->board = $board;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setTopic($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getTopic() === $this) {
                $message->setTopic(null);
            }
        }

        return $this;
    }
    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }

    public function setImageFileName(?string $imageFileName): self
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }
    public function getImageFile(): ?UploadedFile
    {
        return $this->imageFile;
    }

    public function setImageFile(?UploadedFile $imageFile): void
    {
        $this->imageFile = $imageFile;
    }
}

src/Form/BoardType.php
<?php

namespace App\Form;

use App\Entity\Board;
use App\Entity\Categories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Repository\CategoriesRepository;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Type de formulaire pour la création ou la modification d'un board.
 */
class BoardType extends AbstractType
{
    private $categoriesRepository;
    private $security;

    /**
     * Constructeur du formulaire de board.
     *
     * @param CategoriesRepository $categoriesRepository Le repository des catégories.
     */
    public function __construct(CategoriesRepository $categoriesRepository, Security $security)
    {
        $this->categoriesRepository = $categoriesRepository;
        $this->security = $security;
    }

    /**
     * Construit le formulaire de board.
     *
     * @param FormBuilderInterface $builder Le constructeur de formulaire.
     * @param array $options Les options du formulaire.
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // Récupérer les catégories depuis la base de données
        $categories = $this->categoriesRepository->findAll();

        // Récupère l'utilisateur actuellement connecté
        $user = $this->security->getUser();

        $choices = [];

        // Vérifie si l'utilisateur a un rôle admin
        $isAllowed = $this->isUserAllowed($user);

        foreach ($categories as $category) {
            if ($isAllowed) {
                $choices[$category->getCategoryName()] = $category;
            } else {
                if ($this->isUserAllowedToAccessCategories($user, $category)) {
                    $choices[$category->getCategoryName()] = $category;
                }
            }
        }

        // Ajout des champs pour le nom du board et la catégorie
        $builder
            ->add('board_name')
            ->add('category', ChoiceType::class, [
                'choices' => $choices,
                'placeholder' => 'Choose a category',
                'required' => true,
            ]);
    }

    /**
     * Configure les options par défaut pour le formulaire.
     *
     * @param OptionsResolver $resolver Le résolveur pour configurer les options.
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Board::class,
        ]);
    }
    private function isUserAllowedToAccessCategories(?UserInterface $user, Categories $category): bool
    {
        // Si l'utilisateur n'est pas connecté, il n'a pas accès au board
        if (!$user) {
            return false;
        }

        // Récupérez les rôles de l'utilisateur
        $userRoles = $user->getRoles();

        // Récupérez les rôles de la catégorie associée à ce board
        $categoryRoles = $category->getRoles();

        // Vérifiez si l'utilisateur a l'un des rôles associés à cette catégorie
        foreach ($categoryRoles as $role) {
            if (in_array($role->getRoleName(), $userRoles)) {
                // L'utilisateur a accès à la catégorie associée à ce board
                return true;
            }
        }

        // L'utilisateur n'a pas accès à la catégorie s'il ne correspond à aucun rôle associé
        return false;
    }

    private function isUserAllowed(?UserInterface $user): bool
    {
        // Si l'utilisateur n'est pas connecté ou n'a pas l'un des rôles "admin" ou "insider", il n'a pas l'autorisation
        if (!$user || !in_array('admin', $user->getRoles())) {
            return false;
        }

        // L'utilisateur a l'un des rôles "admin" ou "insider" et est autorisé
        return true;
    }
}

src/Controller/BoardController.php
<?php

namespace App\Controller;

use App\Entity\Board;
use App\Form\BoardType;
use App\Repository\BoardRepository;
use App\Repository\TopicRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

#[Route('/board')]
class BoardController extends AbstractController
{
    #[Route('/', name: 'app_board_index', methods: ['GET'])]
    public function index(BoardRepository $boardRepository): Response
    {
        // Récupérez tous les boards depuis le repository
        $boards = $boardRepository->findAll();

        // Si l'utilisateur est un administrateur, affichez tous les boards
        if (!$this->isUserAllowed()) {
            throw new AccessDeniedException('Access denied: You do not have permission to go there.');
        }
        return $this->render('board/index.html.twig', [
            'boards' => $boards,
        ]);
    }



    #[Route('/new', name: 'app_board_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        /**
         * Crée un nouveau board.
         *
         * @param Request $request La requête HTTP
         * @param EntityManagerInterface $entityManager Le gestionnaire d'entités
         * @return Response La réponse HTTP
         */
        // Vérifiez si l'utilisateur est administrateur ou insider avant de permettre l'accès
        if (!$this->isUserAllowed()) {
            throw new AccessDeniedException('Access denied: You do not have permission to create a new board.');
        }
        $board = new Board();
        $form = $this->createForm(BoardType::class, $board);
        $form->handleRequest($request);

        $board->setCreatedAt(new \DateTimeImmutable());

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($board);
            $entityManager->flush();

            return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('board/new.html.twig', [
            'board' => $board,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_board_show', methods: ['GET'])]
    public function show(Board $board, TopicRepository $topicRepository): Response
    {
        /**
         * Affiche les détails d'un board.
         *
         * @param Board $board Le board à afficher
         * @return Response La réponse HTTP contenant les détails du board
         */
        $user = $this->getUser();
        if (!$this->isUserAllowedToAccessBoard($user, $board) && !$this->isUserAllowed()) {
            // L'utilisateur n'est pas autorisé à accéder à ce board
            throw new AccessDeniedException('Access denied: You do not have permission to access this board.');
        }
        $topic = $topicRepository->findAll();
        return $this->render('board/show.html.twig', [
            'board' => $board,
            'topic' => $topic,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_board_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Board $board, EntityManagerInterface $entityManager): Response
    {
        /**
         * Modifie un board existant.
         *
         * @param Request $request La requête HTTP
         * @param Board $board Le board à modifier
         * @param EntityManagerInterface $entityManager Le gestionnaire d'entités
         * @return Response La réponse HTTP
         */
        // Vérifiez si l'utilisateur est administrateur ou insider avant de permettre l'accès
        if (!$this->isUserAllowed()) {
            throw new AccessDeniedException('Access denied: You do not have permission to create a new board.');
        }
        $form = $this->createForm(BoardType::class, $board);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('board/edit.html.twig', [
            'board' => $board,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_board_delete', methods: ['POST'])]
    public function delete(Request $request, Board $board, EntityManagerInterface $entityManager): Response
    {
        /**
         * Supprime un board.
         *
         * @param Request $request La requête HTTP
         * @param Board $board Le board à supprimer
         * @param EntityManagerInterface $entityManager Le gestionnaire d'entités
         * @return Response La réponse HTTP
         */
        // Vérifiez si l'utilisateur est administrateur ou insider avant de permettre l'accès
        if (!$this->isUserAllowed()) {
            throw new AccessDeniedException('Access denied: You do not have permission to create a new board.');
        }
        if ($this->isCsrfTokenValid('delete' . $board->getId(), $request->request->get('_token'))) {
            $entityManager->remove($board);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_board_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * Vérifie si l'utilisateur a accès à un board en fonction de ses rôles et de la catégorie associée.
     *
     * @param UserInterface|null $user L'utilisateur connecté ou null s'il n'est pas connecté
     * @param Board $board Le board auquel l'utilisateur souhaite accéder
     * @return bool true si l'utilisateur est autorisé, sinon false
     */
    private function isUserAllowedToAccessBoard(?UserInterface $user, Board $board): bool
    {
        // Si l'utilisateur n'est pas connecté, il n'a pas accès au board
        if (!$user) {
            return false;
        }

        // Récupérez les rôles de l'utilisateur
        $userRoles = $user->getRoles();

        // Récupérez la catégorie associée à ce board
        $category = $board->getCategory();

        // Vérifiez si l'utilisateur a l'un des rôles associés à cette catégorie
        foreach ($category->getRoles() as $role) {
            if (in_array($role->getRoleName(), $userRoles)) {
                // L'utilisateur a accès à la catégorie associée à ce board
                return true;
            }
        }

        // L'utilisateur n'a pas accès au board s'il ne correspond à aucun rôle associé à la catégorie
        return false;
    }
    private function isUserAllowed(): bool
    {
        // Récupérez l'utilisateur connecté
        $user = $this->getUser();
        // Si l'utilisateur n'est pas connecté ou n'a pas l'un des rôles "admin" ou "insider", il n'a pas l'autorisation
        if (!$user || !in_array('admin', $user->getRoles()) && !in_array('insider', $user->getRoles())) {
            return false;
        }

        // L'utilisateur a l'un des rôles "admin" ou "insider" et est autorisé
        return true;
    }
}

templates/board/_delete_form.html.twig
<form method="post" action="{{ path('app_board_delete', {'id': board.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ board.id) }}">
    <button class="btn">Delete</button>
</form>

templates/board/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/board/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Edit Board{% endblock %}

{% block body %}
<style>
.form-wrapper{
  max-width: 600px; /* Set the maximum width of the form */
  margin: 0 auto; /* Center-align the form horizontally */
  padding: 20px; /* Add some padding for spacing */
  background-color: #f7f7f7; /* Background color for the form */
  border: 1px solid #ddd; /* Border around the form */
  border-radius: 5px; /* Rounded corners */
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle 3D effect */
}
/* Form Fields */
.form-wrapper #board div{
  margin-bottom: 15px; /* Spacing between form groups */
}

.form-wrapper #board label {
    display: block; /* Display labels as blocks for vertical alignment */
    margin-bottom: 5px; /* Spacing below the label */
    font-weight: bold; /* Bold label text */
}

.form-wrapper #board input, .form-wrapper #board #board_category{
    width: 96%;
    padding: 10px; /* Add padding for input fields */
    border: 1px solid #ddd; /* Border for input fields */
    border-radius: 3px; /* Rounded corners for input fields */
}
.form-wrapper #board #board_category{
    width: 100%; /* Make input fields take up the full width */
}



/* Form Buttons */
.form-wrapper .btn{
  display: block; /* Display buttons as blocks for vertical alignment */
  width: 100%; /* Make buttons take up the full width */
  padding: 10px; /* Add padding for buttons */
  background-color: #007bff; /* Button background color */
  color: #fff; /* Button text color */
  border: none; /* Remove button borders */
  border-radius: 3px; /* Rounded corners for buttons */
  cursor: pointer; /* Add a pointer cursor on hover */
  transition: background-color 0.3s; /* Smooth background color transition on hover */
}

.form-button:hover {
  background-color: #0056b3; /* Change button color on hover */
}
</style>
<div class="example-wrapper">
    <h1>Edit Board</h1>
    
    <div class="form-wrapper">

        {{ include('board/_form.html.twig', {'button_label': 'Update'}) }}
    </div>

    <a href="{{ path('app_board_show', {'id': board.id}) }}">back to board</a>

    {{ include('board/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/board/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Board index{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Board Management</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Board_name</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr>
                <td>{{ board.boardName }}</td>
                <td>{{ board.createdAt ? board.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_board_show', {'id': board.id}) }}">show</a>
                    <a href="{{ path('app_board_edit', {'id': board.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<div class="text-center">
    <a href="{{ path('app_board_new') }}">Create a new board</a></br>
    <a href="{{ path('app_home') }}">Back to home</a>
    </div>
    </div>
{% endblock %}

templates/board/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}New Board{% endblock %}

{% block body %}
<style>
.form-wrapper{
  max-width: 600px; /* Set the maximum width of the form */
  margin: 0 auto; /* Center-align the form horizontally */
  padding: 20px; /* Add some padding for spacing */
  background-color: #f7f7f7; /* Background color for the form */
  border: 1px solid #ddd; /* Border around the form */
  border-radius: 5px; /* Rounded corners */
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Box shadow for a subtle 3D effect */
}
/* Form Fields */
.form-wrapper #board div{
  margin-bottom: 15px; /* Spacing between form groups */
}

.form-wrapper #board label {
    display: block; /* Display labels as blocks for vertical alignment */
    margin-bottom: 5px; /* Spacing below the label */
    font-weight: bold; /* Bold label text */
}

.form-wrapper #board input, .form-wrapper #board #board_category{
    width: 96%;
    padding: 10px; /* Add padding for input fields */
    border: 1px solid #ddd; /* Border for input fields */
    border-radius: 3px; /* Rounded corners for input fields */
}
.form-wrapper #board #board_category{
    width: 100%; /* Make input fields take up the full width */
}



/* Form Buttons */
.form-wrapper .btn{
  display: block; /* Display buttons as blocks for vertical alignment */
  width: 100%; /* Make buttons take up the full width */
  padding: 10px; /* Add padding for buttons */
  background-color: #007bff; /* Button background color */
  color: #fff; /* Button text color */
  border: none; /* Remove button borders */
  border-radius: 3px; /* Rounded corners for buttons */
  cursor: pointer; /* Add a pointer cursor on hover */
  transition: background-color 0.3s; /* Smooth background color transition on hover */
}

.form-button:hover {
  background-color: #0056b3; /* Change button color on hover */
}
</style>
<div class="example-wrapper">
    <h1>Create new Board</h1>
    <div class="form-wrapper">
        {{ include('board/_form.html.twig') }}
    </div>
<a href="{{ path('app_home') }}">back to home</a>
</div>
{% endblock %}

templates/board/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Board{% endblock %}

{% block body %}
<style>
.text-center{
    text-align: center;
}
.table th {
    background-color: #f2f2f2;
    display: table-cell;
    padding: 1em;
}
.table th div{
    display: flex;
    justify-content: space-between;
}
</style>
<div class='example-wrapper'>
    <h1>{{board.boardName}}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>
                    {{ board.boardName|upper }} 
                </th>
                <th>
                    <div>
                        Nombre de vues
                        <div>
                        <a href="{{ path('app_board_edit', {'id': board.id}) }}">edit</a>
                        {{ include('board/_delete_form.html.twig') }}
                        <div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
        {% for topic in board.topics %}
            <tr>
                
                <td><a href="{{ path('app_topic_show',{'id':topic.id})}}">{{ topic.title }}</a></td>
                <td>{{ topic.numberView }}</td>
            </tr>
        {% endfor %}</tbody>
    
    </table>
    <div class="text-center">
<a href="{{ path('app_topic_new') }}">Create a new topic</a></br>
    <a href="{{ path('app_categories_show',{'id':board.category.id}) }}">back to category</a>
</div>
</div>
{% endblock %}